{% set name = "localstack-client" %}
{% set version = "0.17" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: a4054744d465ed446c6d4aad2ceb795d5193f44f74b6aa81c8198f8c6e444ef6

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - boto3
    - python

test:
  imports:
    - localstack_client

about:
  home: "https://github.com/localstack/localstack-python-client"
  license: "Apache-2.0"
  license_family: "APACHE"
  license_file: "LICENSE"
  summary: "A lightweight Python client for LocalStack."
  doc_url: "https://pypi.org/project/localstack-client/"
  dev_url: "https://github.com/localstack/localstack-python-client"

extra:
  recipe-maintainers:
    - mwilson8
    - oblute
    - benhuff
