{% set name = "localstack-client" %}
{% set version = "2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/localstack-client-{{ version }}.tar.gz
  sha256: 33b80404b83575eb74c4bda174a0fe85fe7d9c403fa65a893dff3f316bdfb445

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - boto3
    - python >=3.6

test:
  imports:
    - localstack_client
  commands:
    - pip check
  requires:
    - pip
about:
  home: https://github.com/localstack/localstack-python-client
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A lightweight Python client for LocalStack.
  doc_url: https://pypi.org/project/localstack-client/
  dev_url: https://github.com/localstack/localstack-python-client

extra:
  recipe-maintainers:
    - mxr-conda
