{% set name = "localstack-client" %}
{% set version = "2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 67c9da9ea04152b142ecd1ac9a2ae2e231c2a8fcff542faf02d7f9f80843f215

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - boto3
    - python >=3.6

test:
  imports:
    - localstack_client
  commands:
    - pip check
  requires:
    - pip
about:
  home: https://github.com/localstack/localstack-python-client
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A lightweight Python client for LocalStack.
  doc_url: https://pypi.org/project/localstack-client/
  dev_url: https://github.com/localstack/localstack-python-client

extra:
  recipe-maintainers:
    - mxr-conda
